waypoints:
  - x: 0
    y: 0
    id: 0

  - x: 1.25
    y: 7.83
    id: 1

  - x: 4.50
    y: 2.37
    id: 2

  # - x: 8.92
  #   y: 6.54
  #   id: 3

  # - x: 3.06
  #   y: 9.01
  #   id: 4

  - x: 1.25
    y: 7.83
    id: 5
